language: julia
os:
  - linux
julia:
  - 0.5.2
notifications:
  email: false

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install build-essential gfortran perl g++ gcc cmake m4 git
  - sudo apt-get install -y liblapack-dev liblapack-doc liblapack3gf
  - sudo apt-get install -y libblas-dev libblas-doc libblas3gf
  - echo `pwd`
install:
  - ls ./deps
  - ls -lh ./deps/travis-install-mpi.sh
  - sudo ./deps/travis-install-mpi.sh mpich3
  - ls ./
  - ls ../
  - julia -e 'Pkg.init()'
  - cd ~/.julia/v0.4/
  - julia -e 'Pkg.clone("https://github.com/OptimalDesignLab/PETSc2.jl.git")'
  - cd ./PETSc2/
  - export PETSC_DIR=""  # avoid building petsc here
  - export PETSC_ARCH=""
  - julia ./deps/build.jl
  - unset PETSC_DIR  # have the tests build PETSc
  - unset PETSC_ARCH
 
  
# uncomment the following lines to override the default test script
script:
  #  - cd ./deps
  #  - julia -e 'Pkg.init()'
  #  - julia ./build.jl
  #  - cd ..
  - echo $HOME
  - ./test/runtests.sh  # this builds PETSc
#  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("PETSc"); Pkg.test("PETSc"; coverage=true)'
#  - julia --check-bounds=yes ./test/test_singlereal.jl
